### ISSUE TITLE
Battle Results Screen Prototype

### ISSUE THREAD

**Issue by Birgerev** [Birgerev/ww2-shooter#72]

**Comment by Birgerev** [comment]
@TinySoftOnenote lol gö detta

**Comment by Birgerev** [comment]
@TinySoftOnenote merge, sluta göra alla nya features i samma branch

**Comment by TinySoftOnenote** [comment]
i wut?

**Comment by Birgerev** [comment]
big lol
du borde merga branchen med denna feature till master

**Comment by Birgerev** [comment]
och sluta lägga alla dina features i samma branch, det blir conflicts
